### ISSUE TITLE
Initializer example throws a deprecation

### ISSUE THREAD

**Issue by nickschot** [edgycircle/ember-pikaday#123]
Current version of the initializer shown in the README throws a deprecation in (at least) Ember 2.10+.

```
DEPRECATION: The `initialize` method for Application initializer 'setup-pikaday-i18n' should take only one argument - `App`, an instance of an `Application`. [deprecation id: ember-application.app-initializer-initialize-arguments] See http://emberjs.com/deprecations/v2.x/#toc_initializer-arity for more details.
        at logDeprecationStackTrace (http://localhost:4200/assets/vendor.js:21945:19)
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:22056:7)
        at raiseOnDeprecation (http://localhost:4200/assets/vendor.js:21975:12)
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:22056:7)
        at invoke (http://localhost:4200/assets/vendor.js:22072:7)
        at deprecate (http://localhost:4200/assets/vendor.js:22040:32)
        at Object.deprecate (http://localhost:4200/assets/vendor.js:33059:37)
        at http://localhost:4200/assets/vendor.js:20956:23
        at Vertices.each (http://localhost:4200/assets/vendor.js:19030:13)
```

**Comment by duizendnegen** [comment]
Good catch - welcoming a PR :)

**Comment by nickschot** [comment]
I'd have to look into how to fix this. I'm not really familiar with intializers/injection. I might be able to look into this later this week.

**Comment by duizendnegen** [comment]
It _should_ be merely registering it on the application, not in any container or so. Have a look at http://emberjs.com/deprecations/v2.x/#toc_initializer-arity.

**Comment by nickschot** [comment]
Indeed, registering it on the application and removing the container argument fixes it 👍. I'll make a PR.
