### ISSUE TITLE
Deprecation Warning: didUpdateAttrs will stop receiving arguments

### ISSUE THREAD

**Issue by tsteuwer** [edgycircle/ember-pikaday#147]
https://emberjs.com/deprecations/v2.x/#toc_arguments-in-component-lifecycle-hooks

```
DEPRECATION: [DEPRECATED] Ember will stop passing arguments to component lifecycle hooks. Please change `<app-name-here@component:pikaday-input::ember885>#didUpdateAttrs` to stop taking arguments. [deprecation id: ember-views.lifecycle-hook-arguments] See http://emberjs.com/deprecations/v2.x/#toc_arguments-in-component-lifecycle-hooks for more details.
        at logDeprecationStackTrace (http://172.19.15.43:4200/assets/vendor.js:23441:19)
        at HANDLERS.(anonymous function) (http://172.19.15.43:4200/assets/vendor.js:23651:7)
        at raiseOnDeprecation (http://172.19.15.43:4200/assets/vendor.js:23471:12)
        at HANDLERS.(anonymous function) (http://172.19.15.43:4200/assets/vendor.js:23651:7)
        at invoke (http://172.19.15.43:4200/assets/vendor.js:23667:7)
        at deprecate (http://172.19.15.43:4200/assets/vendor.js:23536:32)
        at Object.deprecate (http://172.19.15.43:4200/assets/vendor.js:23975:37)
        at Class.exports.default._emberMetal.Mixin.create._Mixin$create.init (http://172.19.15.43:4200/assets/vendor.js:59548:17)
        at Class.superWrapper (http://172.19.15.43:4200/assets/vendor.js:58549:22)
```

**Comment by duizendnegen** [comment]
Welcoming a PR :)

**Comment by tsteuwer** [comment]
@duizendnegen looking into it ;)

**Comment by tsteuwer** [comment]
@duizendnegen done and done!
