### ISSUE TITLE
Deprecation warning with latest moment JS

### ISSUE THREAD

**Issue by mdentremont** [edgycircle/ember-pikaday#93]
After updating to the latest version of moment I'm seeing the following deprecation warning which originates in Pikaday:
```
Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: [object Object]
Error
    at Function.createFromInputFallback (http://localhost:7357/assets/vendor/moment/min/moment.min.js:17:1)
    at eb (http://localhost:7357/assets/vendor/moment/min/moment.min.js:129:1)
    at pb (http://localhost:7357/assets/vendor/moment/min/moment.min.js:169:1)
    at ob (http://localhost:7357/assets/vendor/moment/min/moment.min.js:169:1)
    at nb (http://localhost:7357/assets/vendor/moment/min/moment.min.js:167:1)
    at qb (http://localhost:7357/assets/vendor/moment/min/moment.min.js:174:1)
    at rb (http://localhost:7357/assets/vendor/moment/min/moment.min.js:174:1)
    at a (http://localhost:7357/assets/vendor/moment/min/moment.min.js:6:1)
    at comparableMoment (http://localhost:7357/assets/moment/index.js:29:1)
    at Class.setPikadayDate (http://localhost:7357/assets/ember-pikaday/components/pikaday-input.js:86:1)
```

edit: After downgrading moment I'm still seeing this - I think it might be linked to the latest version of ember-pikaday

**Comment by stravid** [comment]
Thanks for the report, I'm currently swamped at work and will try to take a look as fast as possible.

**Comment by mdentremont** [comment]
@stravid This fixes it for me: https://github.com/edgycircle/ember-pikaday/pull/94

**Comment by mdentremont** [comment]
@stravid: All you have to do is hit the green button 😄 #94 (..and put out a new release)

**Comment by stravid** [comment]
@mdentremont I tried to reproduce the error but could not do so? When does this happen? With what versions of Moment.js? (Maybe you have a repository to reproduce the problem?)

(I want to understand the problem before clicking merge in case you are wondering :))

**Comment by mdentremont** [comment]
Using moment 2.14.1 - unfortunately the repository I'm using is private, so I can't share it 😞.

Here is a link which explains the reasoning for the deprecation: http://momentjs.com/guides/#/warnings/js-date/ (the long version is here https://github.com/moment/moment/issues/1407)

**Comment by stravid** [comment]
Thanks for the version number, that did it :)

**Comment by mdentremont** [comment]
Awesome!
